/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type HeroSection = {
  _id: string;
  _type: "heroSection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
};

export type Sale = {
  _id: string;
  _type: "sale";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  discountAmount?: number;
  couponCode?: string;
  validFrom?: string;
  validUntil?: string;
  isActive?: boolean;
};

export type CollectionType = {
  _id: string;
  _type: "collectionType";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  showOnCollectionsPage?: boolean;
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  customerName?: string;
  clerkUserId?: string;
  customerEmail?: string;
  shippingAddress?: string;
  products?: Array<{
    product?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "product";
    };
    quantity?: number;
    size?: string;
    _key: string;
  }>;
  totalAmount?: number;
  amountDiscount?: number;
  status?: "pending" | "processing" | "shipped" | "delivered" | "cancelled";
  orderDate?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  price?: number;
  oldPrice?: number;
  description?: string;
  category?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  collections?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "collectionType";
  }>;
  size?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "size";
  };
  colors?: Array<string>;
  stock?: number;
  featured?: boolean;
  tags?: Array<string>;
  sku?: string;
  createdAt?: string;
  updatedAt?: string;
};

export type Size = {
  _id: string;
  _type: "size";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  ageGroup?: string;
  slug?: Slug;
  kameezLength?: number;
  sleevesLength?: number;
  shoulder?: number;
  fitting?: "regular" | "slim" | "loose";
  chest?: number;
  shalwarLength?: number;
  paienchaWidth?: number;
  sleevesStyle?: "golla" | "cuff" | "straight" | "none";
  description?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = HeroSection | Sale | CollectionType | Order | Category | Product | Size | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/products/getAllCategories.ts
// Variable: ALL_CATEGORIES_QUERY
// Query: *[            _type == "category"        ] | order(title asc)
export type ALL_CATEGORIES_QUERYResult = Array<{
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
}>;

// Source: ./src/sanity/lib/products/getAllCollection.ts
// Variable: ALL_COLLECTION_QUERY
// Query: *[            _type == "collectionType"        ] | order(title asc)
export type ALL_COLLECTION_QUERYResult = Array<{
  _id: string;
  _type: "collectionType";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  showOnCollectionsPage?: boolean;
}>;

// Source: ./src/sanity/lib/products/getHeroImages.ts
// Variable: ALL_HEROIMAGES_QUERY
// Query: *[_type == "heroSection"]{  "imageUrl": image.asset->url,  alt}
export type ALL_HEROIMAGES_QUERYResult = Array<{
  imageUrl: string | null;
  alt: string | null;
}>;

// Source: ./src/sanity/lib/products/getProductBySize.ts
// Variable: PRODUCT_BY_SIZE
// Query: *[_type == "product" && size->ageGroup == $ageGroup] {  _id,  title,  slug,  price,  image,  size->{    _id,    name,    ageGroup,    slug  }}
export type PRODUCT_BY_SIZEResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  price: number | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  size: {
    _id: string;
    name: string | null;
    ageGroup: string | null;
    slug: Slug | null;
  } | null;
}>;

// Source: ./src/sanity/lib/products/getProductBySlug.ts
// Variable: PRODUCT_BY_SLUG
// Query: *[_type == "product" && slug.current == $slug][0]{    _id,    title,    slug,    price,    oldPrice,    stock,    images,    colors,    featured,    sku,    // references:    "size": size->{      _id,      name    },    "categories": category[]->{      _id,      name,    },    "collectionType": collections[]->{      _id,      title,    }  }
export type PRODUCT_BY_SLUGResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  price: number | null;
  oldPrice: number | null;
  stock: number | null;
  images: null;
  colors: Array<string> | null;
  featured: boolean | null;
  sku: string | null;
  size: {
    _id: string;
    name: string | null;
  } | null;
  categories: Array<{
    _id: string;
    name: string | null;
  }> | null;
  collectionType: Array<{
    _id: string;
    title: string | null;
  }> | null;
} | null;

// Source: ./src/sanity/lib/products/searchProductByName.ts
// Variable: PRODUCT_SEARCH_QUERY
// Query: *[            _type == "product"            && name match $searchParam        ] | order(name asc)
export type PRODUCT_SEARCH_QUERYResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  price?: number;
  oldPrice?: number;
  description?: string;
  category?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  collections?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "collectionType";
  }>;
  size?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "size";
  };
  colors?: Array<string>;
  stock?: number;
  featured?: boolean;
  tags?: Array<string>;
  sku?: string;
  createdAt?: string;
  updatedAt?: string;
}>;

// Source: ./src/sanity/lib/sales/getActiveSaleByCouponCode.ts
// Variable: Active_SALE_BY_COUPON_QUERY
// Query: *[            _type == "sale"            && isActive == true            && couponCode == $couponCode        ] | order(validFrom desc)[0]
export type Active_SALE_BY_COUPON_QUERYResult = {
  _id: string;
  _type: "sale";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  discountAmount?: number;
  couponCode?: string;
  validFrom?: string;
  validUntil?: string;
  isActive?: boolean;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n        *[\n            _type == \"category\"\n        ] | order(title asc)\n        ": ALL_CATEGORIES_QUERYResult;
    "\n        *[\n            _type == \"collectionType\"\n        ] | order(title asc)\n        ": ALL_COLLECTION_QUERYResult;
    "\n        *[_type == \"heroSection\"]{\n  \"imageUrl\": image.asset->url,\n  alt\n}\n\n": ALL_HEROIMAGES_QUERYResult;
    "\n  *[_type == \"product\" && size->ageGroup == $ageGroup] {\n  _id,\n  title,\n  slug,\n  price,\n  image,\n  size->{\n    _id,\n    name,\n    ageGroup,\n    slug\n  }\n}\n\n\n    ": PRODUCT_BY_SIZEResult;
    "\n    *[_type == \"product\" && slug.current == $slug][0]{\n    _id,\n    title,\n    slug,\n    price,\n    oldPrice,\n    stock,\n    images,\n    colors,\n    featured,\n    sku,\n\n    // references:\n    \"size\": size->{\n      _id,\n      name\n    },\n    \"categories\": category[]->{\n      _id,\n      name,\n    },\n    \"collectionType\": collections[]->{\n      _id,\n      title,\n    }\n  }\n    ": PRODUCT_BY_SLUGResult;
    "\n        *[\n            _type == \"product\"\n            && name match $searchParam\n        ] | order(name asc)\n        ": PRODUCT_SEARCH_QUERYResult;
    "\n        *[\n            _type == \"sale\"\n            && isActive == true\n            && couponCode == $couponCode\n        ] | order(validFrom desc)[0]\n        ": Active_SALE_BY_COUPON_QUERYResult;
  }
}
